env_config:
  env_name:
    - verbal-Haiku-v0
    - verbal-Tanka-v0
    - verbal-LineSyllableConstrainedPoem-v0
    - verbal-SyllableConstrainedPoem-v0
  feedback:
    - 0.0

agent_config:
  file:
    - configs/agent_configs/basic_agent.yaml
    - configs/agent_configs/posterior_agent.yaml
    - configs/agent_configs/reflexion_agent.yaml
    - configs/agent_configs/tot_agent.yaml