env_config:
  env_name:
    - verbal-SyllableConstrainedPoem-v0
  feedback: [0, 0.5, 1.0]
  syllable: [5, 6, 7, 8]

agent_config:
  file:
    - configs/agent_configs/basic_agent.yaml
    - configs/agent_configs/posterior_agent.yaml
    - configs/agent_configs/reflexion_agent.yaml