title: LLF-Bench
description: Benchmarking text-based AI agents.
authors: Ching-An Cheng, Andrey Kolobov, Dipendra Misra, Allen Nie, Adith Swaminathan
buttons:
  Paper: 'https://www.microsoft.com/en-us/research/publication/llf-bench-benchmark-for-interactive-learning-from-language-feedback/'
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
